meta:
  url: https://gabelluardo.github.io/plenaria2021
  title: Plenaria 2021
  description:
  siteName: plenaria2021
  sns: ["twitter"]
slide:
  loop: false
  targetBlank: true
  ui:
    sidebar: false
    pagination: progressbar
    effect:
  code:
    theme: okaidia
